import Head from 'next/head';
import Image from 'next/image';
import { StyledDiv } from '../styles/index.styles';
import fs from 'fs/promises';
import path from 'path';

export default function Home(props) {
  const test = [1, 2, 3, 4, 5, 6, 7, 8];
  const { data } = props;
  // console.log(props.data.products);
  // console.log(data);

  return (
    <StyledDiv>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='section-center'>
        <h1>second commit</h1>
        <ul>
          {data.map((item, index) => {
            return <ListItem key={index} item={item} />;
          })}
        </ul>
      </section>
    </StyledDiv>
  );
}

export async function getStaticProps(context) {
  console.log('hello from the backend');
  console.log(context);
  const filePath = path.join(process.cwd(), 'data', 'dummy.data.json');
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData);
  return {
    props: { data: data.products },
    revalidate: 10,
    notFound: false,
  };
}

const ListItem = () => {
  return <li>hello</li>;
};
