import Head from 'next/head';
import Image from 'next/image';
import { StyledDiv } from '../styles/index.styles';
import fs from 'fs/promises';
import path from 'path';
import Link from 'next/link';

export default function Home(props) {
  const { data } = props;

  return (
    <StyledDiv>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='section-center'>
        <h1>second commit</h1>
        <ul>
          {data.map((item, index) => {
            return <ListItem key={item.id} {...item} />;
          })}
        </ul>
      </section>
    </StyledDiv>
  );
}

export async function getStaticProps(context) {
  console.log('hello from the backend 1');

  const filePath = path.join(process.cwd(), 'data', 'dummy.data.json');
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData);

  return {
    props: { data: data.products },
    revalidate: 10,
    notFound: false,
  };
}

const ListItem = (item) => {
  const { id, title } = item;

  return (
    <>
      <Link href={`/${id}`}>
        <div>
          <p>{id}</p>
          <p>{title}</p>
        </div>
      </Link>
    </>
  );
};
