import Head from 'next/head';
import Image from 'next/image';
import { StyledDiv } from '../styles/index.styles';

export default function Home() {
  const test = [1, 2, 3, 4, 5, 6, 7, 8];

  return (
    <StyledDiv>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='section-center'>
        <h1>second commit</h1>
        <ul>
          {test.map((item) => {
            return <ListItem key={item} item={item} />;
          })}
        </ul>
      </section>
    </StyledDiv>
  );
}

const ListItem = () => {
  return (
    <li>
      <img
        src='https://cdn.pixabay.com/photo/2022/01/23/16/29/banana-peel-6961349_1280.jpg'
        alt=''
      />
      <p>caption</p>
      <button>button</button>
    </li>
  );
};
